kind: Deployment
apiVersion: apps/v1
metadata:
  name: doppelgaenger-websocket
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"doppelgaenger-websocket:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"app\")].image"}]'
  labels:
    app.kubernetes.io/name: doppelgaenger-websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: doppelgaenger-websocket
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: doppelgaenger-websocket
    spec:
      enableServiceLinks: false
      containers:
        - name: app
          image: doppelgaenger-websocket
          imagePullPolicy: Always
          env:
            - name: MONGODB__URL
              valueFrom:
                secretKeyRef:
                  name: doppelgaenger-config
                  key: mongodb.url
            - name: DATABASE
              value: twin-db
            - name: DROGUE_APP
              value: ctron-opcua
            - name: INDEX__COLS
              value: "row-cols-1 row-cols-lg-2 g-4"
          ports:
            - containerPort: 8082
              name: web
          livenessProbe:
            httpGet:
              port: 8082
              path: /health
          readinessProbe:
            httpGet:
              port: 8082
              path: /health
